<center><h1 style="font-size: 50px; font-weight:bolder;">DS 2.2: Deep Learning</h1></center>

## What is Deep Learning?
#### Difference between Machine learning and Deep Learning:
Machine learning is used for 
#### What is a Neural Network?
A newural network is a deep learning model based off the human brain. The way we process information is that we have many neurons and they process data, then pass the data to a new neuron and let it process it too. This process repeats many times till we understand the data. The neural network works by also passing data through nodes called neurons and creating a sigmoid function that then passes the data to a new neuron until we get a result. Next the neural network compares that answer to the actual answer and improves on it by running through the neural network again.

## Deep Learning:
#### What is a vector?  
A vector is "number arguments in horizontal or vertical order (in one dimensional space)" If your data included a car's position and time you could derrive its velocity, a one dimensional vector that explains both information.
#### What is a matrix?
2 dimensional arrangements of numbers. Greyscale photos can be labeled using black and white intensity.
#### What is tensor?
3 dimensional arrangements of numbers. Color for instance (R, G, B).

### Make a vector with numpy

In [7]:
import numpy as np

In [8]:
v = np.array([5,2,1])
print(v)
print(v.shape)

[5 2 1]
(3,)


In [10]:
v = np.array([[5,2,1]])
print(v)
print(v.shape)

[[5 2 1]]
(1, 3)


In [11]:
v_t = np.transpose(v)
print(v_t)
v_t.shape

[[5]
 [2]
 [1]]


(3, 1)

In [15]:
v[0][1]

2

### Make a matrix with numpy

In [16]:
v = np.array([[1,2,3],[2, 0, 1]])
print(v)
print(v.shape)
print(v.size)

[[1 2 3]
 [2 0 1]]
(2, 3)
6


In [17]:
v_t = np.transpose(v)
print(v_t)
print(v_t.shape)
print(v_t.size)

[[1 2]
 [2 0]
 [3 1]]
(3, 2)
6


### Arrange or Reshape the matrix (2D array or 2D Tensor)

In [44]:
v = np.array([[1,2,3],[2, 0, 1]])
print("v.reshape(3,2)")
print(v.reshape(3,2))

# By applying the following reshape, we transform the matrix into 3D Tensor
print("\nv.reshape(3,1,2)")
print(v.reshape(3,1,2))
print("\nv.reshape(-1,1,2)")
print(v.reshape(-1,1,2))

v.reshape(3,2)
[[1 2]
 [3 2]
 [0 1]]

v.reshape(3,1,2)
[[[1 2]]

 [[3 2]]

 [[0 1]]]

v.reshape(-1,1,2)
[[[1 2]]

 [[3 2]]

 [[0 1]]]


### Make a 3D Tensor in numpy

In [52]:
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)

# The first element of shape shows how many, and the second and third elements shows the dimension
print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]
(2, 2, 3)


In [53]:
print(v[0])

[[1. 2. 3.]
 [4. 5. 6.]]


In [73]:
print(v.reshape(3,2,-1))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


In [67]:
print(v.reshape(3,2,2))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


### Make a 4D Tensor in numpy

In [75]:
v = np.zeros((2, 3, 5, 5))
print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [83]:
v = np.zeros((2, 2, 3, 5, 5))
print(v.shape)
print(v)
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

(2, 2, 3, 5, 5)
[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0.